version: '3.8'

services:
  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: ai-website-builder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AI Website Builder Backend with Neon
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-website-builder-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}  # Neon connection string
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 3000
      API_PREFIX: api/v1
      CORS_ORIGIN: http://localhost:3000
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 100
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
